// Offline authoring library for the 15 bundled catalog levels (Ticket 31).
//
// This is the Flutter-free, deterministic core the `generar_niveles.dart`
// script orchestrates. It is split out from the script so it can be unit-tested
// directly (no `dart:io`, no asset bundle).
//
// What ticket 31 adds on top of the original tool:
//   • shape rotation — each authored level carries the shape mask ticket 23's
//     [RepertorioFormas] assigns to its index (level 1 → Cuadrado, 2 → Corazón,
//     …), so the rotation starts at Level 1 and is continuous into the endless
//     tail. The repertoire is *reused*, never re-declared here.
//   • raised difficulty bands — the grid floor is 7×7: levels 1–5 → 7×7,
//     6–10 → 8×8, 11–15 → 9×9 (PRD §12 req 2), tuned in one place ([perfilNivel]).
//   • sparse boards — absent positions (outside the shape) are simply omitted
//     from the serialized `cells`; there is no filler and no `type: "absent"`
//     marker. The runtime loader treats an omitted position as absent.

import 'package:arrowmaze/application/generadores/configuracion_generacion.dart';
import 'package:arrowmaze/application/generadores/generacion_aleatoria_nivel.dart';
import 'package:arrowmaze/application/generadores/generador_nivel_base.dart';
import 'package:arrowmaze/domain/entities/celda.dart';
import 'package:arrowmaze/domain/entities/fabrica_celdas_estandar.dart';
import 'package:arrowmaze/domain/entities/trayectoria.dart';
import 'package:arrowmaze/domain/grafo_tablero.dart';
import 'package:arrowmaze/domain/niveles/mascara_forma.dart';
import 'package:arrowmaze/domain/niveles/repertorio_formas.dart';
import 'package:arrowmaze/domain/solver.dart';
import 'package:arrowmaze/domain/value_objects/direccion.dart';
import 'package:arrowmaze/domain/value_objects/posicion.dart';

/// The number of bundled catalog levels.
const totalNivelesCatalogo = 15;

/// Stable display names per level (1-indexed), preserved from the prior catalog.
const nombresCatalogo = <String>[
  'Interlock', 'Crosswind', 'Deadlock', 'Aperture', 'Zephyr',
  'Tangle', 'Gridlock', 'Overpass', 'Maelstrom', 'Conduit',
  'Spire', 'Labyrinth', 'Citadel', 'Vortex', 'Apex',
];

/// The board edge, difficulty label, and target trajectory count for one level.
class PerfilCatalogo {
  /// Binds the band parameters for one level.
  const PerfilCatalogo({
    required this.lado,
    required this.dificultad,
    required this.objetivoTray,
  });

  /// Board edge (square boards: `lado × lado`).
  final int lado;

  /// Difficulty label written to the asset header (FACIL/MEDIO/DIFICIL ordinal).
  final String dificultad;

  /// Desired trajectory count. Generation stops at the first seed that reaches
  /// it (a good, interlocking board) — this is what rejects the generator's
  /// degenerate 2-trajectory "snake" fallback (AC3). Kept ≥ 3 so a two-arrow
  /// board is never *preferred*; where the shape/size cannot reach it, the
  /// most-interlocking board found is used instead (best effort).
  final int objetivoTray;
}

/// The single source of truth for the difficulty curve.
///
/// Grid floor is 7×7 (PRD §12 req 2) and the board grows **one row/column every
/// level**, so difficulty ramps hard: level 1 is 7×7 (49 cells) and level 15 is
/// 21×21 (441 cells) — far beyond a 9×9 — each shaped board packing dozens of
/// arrows. Size and shape (rotation) stay orthogonal axes; retune the ramp here
/// and nowhere else.
PerfilCatalogo perfilNivel(int numero) {
  final lado = 7 + (numero - 1);
  final dificultad = numero <= 5
      ? 'easy'
      : numero <= 10
          ? 'medium'
          : 'hard';
  return PerfilCatalogo(lado: lado, dificultad: dificultad, objetivoTray: 3);
}

/// The shape mask for level [numero], drawn **from ticket 23's repertoire**.
///
/// This is the only place the tool asks for a shape; it never re-declares the
/// shape order, so the authored rotation and the endless tail share one source
/// of truth (AC1/AC2).
MascaraForma formaDeNivel(int numero) =>
    RepertorioFormas().formaParaIndice(numero);

/// Builds the complete asset JSON for one catalog level: a shaped, masked,
/// **sparse** board whose arrows are solvable by construction.
///
/// The board is generated by the engine's own reverse-carving generator, masked
/// to the level's shape, then round-trip verified (solvable, arrow-length ≥ 2,
/// correct absent positions) before being returned. Throws [StateError] if a
/// solvable masked board cannot be produced within the search budget.
Map<String, dynamic> generarNivelJson(int numero) {
  final perfil = perfilNivel(numero);
  final lado = perfil.lado;
  final ausentes = formaDeNivel(numero).ausentes(lado, lado);

  final trayectorias = _generarTrayectorias(numero, lado, ausentes, perfil);
  final json = _aJsonNivel(
    numero: numero,
    nombre: nombresCatalogo[numero - 1],
    dificultad: perfil.dificultad,
    lado: lado,
    trayectorias: trayectorias,
  );

  _verificarRoundTrip(json, lado, ausentes);
  return json;
}

/// Reconstructs the runtime board from an asset JSON exactly as the loader does:
/// arrow cells are grouped into trajectories and every grid position **omitted**
/// from `cells` is treated as absent (void). This is the shared definition of
/// the sparse → absent mapping used by both round-trip verification and tests.
GrafoTablero construirTablero(Map<String, dynamic> json) {
  const fabrica = FabricaCeldasEstandar();
  final filas = json['rows'] as int;
  final columnas = json['cols'] as int;
  final celdas = (json['cells'] as List<dynamic>).cast<Map<String, dynamic>>();

  final agrupadas = <int, Map<String, dynamic>>{};
  final presentes = <Posicion>{};
  for (final celda in celdas) {
    final pos = Posicion.en(
      fila: celda['row'] as int,
      columna: celda['col'] as int,
    );
    presentes.add(pos);
    if (celda['type'] != 'arrow') continue;
    final id = celda['id'] as int;
    agrupadas.putIfAbsent(
      id,
      () => {
        'id': id,
        'head': celda['direction'],
        'cells': <Map<String, dynamic>>[],
      },
    );
    (agrupadas[id]!['cells'] as List<Map<String, dynamic>>)
        .add({'row': celda['row'], 'col': celda['col']});
  }

  final ausentes = <Posicion>{};
  for (var f = 0; f < filas; f++) {
    for (var c = 0; c < columnas; c++) {
      final pos = Posicion.en(fila: f, columna: c);
      if (!presentes.contains(pos)) ausentes.add(pos);
    }
  }

  final trayectorias = agrupadas.values.map(fabrica.crearTrayectoria).toList();
  return GrafoTablero.desde(
    filas: filas,
    columnas: columnas,
    trayectorias: trayectorias,
    ausentes: ausentes,
  );
}

/// Per-level seed search budget. Disjoint per-level ranges (see [_inicioSemilla])
/// stay well under this, so every level's chosen seed — and thus its layout — is
/// unique and reproducible across runs. Kept modest because generation stops as
/// soon as the interlocking target is met; only a shape/size that cannot reach
/// the target scans the whole budget.
const _presupuestoBusqueda = 1000;

/// The start of level [numero]'s private, non-overlapping seed range.
int _inicioSemilla(int numero) => numero * 1000000;

/// Chooses the trajectories for one level from its private seed range.
///
/// Scans deterministically and returns the **first** masked board that reaches
/// the interlocking target (rejecting the degenerate 2-trajectory snake). If no
/// seed reaches the target within the budget — some shapes at the raised sizes
/// (e.g. a thin star on 9×9) cannot be carved into 3+ interlocking arrows by the
/// ticket-23 generator — the most-interlocking board found is used instead, so
/// generation is always deterministic and never fails.
List<Trayectoria> _generarTrayectorias(
  int numero,
  int lado,
  Set<Posicion> ausentes,
  PerfilCatalogo perfil,
) {
  final inicio = _inicioSemilla(numero);
  List<Trayectoria>? mejor;
  for (var i = 0; i < _presupuestoBusqueda; i++) {
    final generador = GeneracionAleatoriaNivel(semilla: inicio + i);
    final tablero = generador.generar(ConfiguracionGeneracion(
      filas: lado,
      columnas: lado,
      ausentes: ausentes,
    ));
    if (tablero == null) continue;
    final trayectorias =
        _extraerTrayectorias(tablero as GrafoTablero, lado, ausentes);
    if (trayectorias.length >= perfil.objetivoTray) {
      return trayectorias;
    }
    if (mejor == null || trayectorias.length > mejor.length) {
      mejor = trayectorias;
    }
  }
  if (mejor != null && mejor.isNotEmpty) return mejor;
  throw StateError(
    'No se pudo generar el nivel $numero (${lado}x$lado, '
    '${formaDeNivel(numero).nombre}).',
  );
}

/// Reads back every trajectory from a populated board, in stable id order,
/// skipping absent positions.
List<Trayectoria> _extraerTrayectorias(
  GrafoTablero tablero,
  int lado,
  Set<Posicion> ausentes,
) {
  final porId = <int, Trayectoria>{};
  for (var f = 0; f < lado; f++) {
    for (var c = 0; c < lado; c++) {
      final pos = Posicion.en(fila: f, columna: c);
      if (ausentes.contains(pos)) continue;
      final t = tablero.trayectoriaEn(pos);
      if (t != null) porId.putIfAbsent(t.id, () => t);
    }
  }
  final lista = porId.values.toList()..sort((a, b) => a.id.compareTo(b.id));
  return lista;
}

/// Serializes a level to the asset JSON the loader understands: arrow cells
/// grouped by trajectory `id`, every cell carrying the head's `direction` token.
///
/// Absent positions carry no arrow, so they simply never appear here — the board
/// is **sparse** with no filler cells.
Map<String, dynamic> _aJsonNivel({
  required int numero,
  required String nombre,
  required String dificultad,
  required int lado,
  required List<Trayectoria> trayectorias,
}) {
  final celdas = <Map<String, dynamic>>[];
  for (final t in trayectorias) {
    final token = _tokenDireccion(t.direccionCabeza);
    for (final seg in t.segmentos) {
      celdas.add({
        'row': seg.fila,
        'col': seg.columna,
        'type': 'arrow',
        'id': t.id,
        'direction': token,
      });
    }
  }

  return {
    'id': numero,
    'name': nombre,
    'difficulty': dificultad,
    'rows': lado,
    'cols': lado,
    // player_start/exit are decorative metadata only — the win condition is an
    // empty board (all trajectories cleared), not reaching a cell. Kept for
    // format parity with the existing assets.
    'player_start': {'row': 0, 'col': 0},
    'exit': {'row': lado - 1, 'col': lado - 1},
    'cells': celdas,
  };
}

/// Re-parses an in-memory level JSON the way the runtime loader does and asserts
/// it builds a valid, solvable board with the expected shape. Throws on any
/// failure so a broken file is never emitted.
void _verificarRoundTrip(
  Map<String, dynamic> json,
  int lado,
  Set<Posicion> ausentes,
) {
  final tablero = construirTablero(json);

  // Every arrow path must span at least [minLongitudFlecha] cells.
  final vistas = <int>{};
  for (var f = 0; f < lado; f++) {
    for (var c = 0; c < lado; c++) {
      final pos = Posicion.en(fila: f, columna: c);
      final t = tablero.trayectoriaEn(pos);
      if (t != null && vistas.add(t.id) && t.segmentos.length < minLongitudFlecha) {
        throw StateError('Trayectoria ${t.id} más corta que el mínimo.');
      }
    }
  }

  // Shape sanity: absent positions are void; every playable position is an arrow
  // segment (100% density within the mask — a real, gap-free puzzle).
  for (var f = 0; f < lado; f++) {
    for (var c = 0; c < lado; c++) {
      final pos = Posicion.en(fila: f, columna: c);
      final celda = tablero.celdaEn(pos);
      if (ausentes.contains(pos)) {
        if (celda is! CeldaAusente) {
          throw StateError('Posición absent ($f,$c) no es CeldaAusente.');
        }
      } else if (celda is! CeldaFlecha) {
        throw StateError('Celda vacía en ($f,$c): la forma no está llena.');
      }
    }
  }

  // Solvability last: esSolvable greedily empties the board in place.
  if (!Solver.esSolvable(tablero)) {
    throw StateError('El nivel generado no es resoluble.');
  }
}

String _tokenDireccion(Direccion d) {
  if (d == Direccion.arriba) return 'UP';
  if (d == Direccion.abajo) return 'DOWN';
  if (d == Direccion.izquierda) return 'LEFT';
  if (d == Direccion.derecha) return 'RIGHT';
  throw ArgumentError.value(d, 'direccion', 'Dirección desconocida');
}
